### ISSUE TITLE
Show or add expand/contract button markup via JavaScript

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-expandables#55] opened 2015-09-09 20:13 UTC
Ideally the expandables wouldn't display the show/hide buttons at all when JS is turned off:

![screen shot 2015-09-09 at 4 10 50 pm](https://cloud.githubusercontent.com/assets/704760/9772979/8c1dd6ca-570d-11e5-8e47-d6831f6a6f09.png)

Have them default to either `display:none` or not being part of the DOM at all and use the expandables JS script to change their display or add them to the DOM.

**Comment by sebworks** [comment] 2015-09-09 20:33
I'm currently working on a fix for this.

**Comment by KimberlyMunoz** [comment] 2015-11-05 01:08
Duplicate of #40

**Closed as completed by KimberlyMunoz** 2015-11-05 01:08 UTC

**Comment by anselmbradford** [comment] 2015-11-05 15:22
Reference fix in https://github.com/cfpb/cfgov-refresh/pull/1134
